---
- name: This playbook will have apache complete stack
  hosts: myservers
  tasks:
   - name: Please install apache2
     package:
         name: apache2
         state: present
   - name: Please start service as well
     service:
        name: apache2
        state: started     
               

   - name: Copy index file 
     copy:
       src: /tmp/index.html
       dest: /var/www/html
